name: Run app.py on Change

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Content
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache Python Packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python Script
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: |
          python app.py

      - name: Commit Changes
        run: |
          git config --local user.email "dilukshashamal2001@gmail.com"
          git config --local user.name "dilukshashamal"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Updated logs from main.py" --allow-empty

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Use your PAT here
          branch: main
