name: Run app.py on Change

on:
  push:
    branches: 
      - main # Runs the workflow on push events to the main branch
  pull_request:
    branches: 
      - main # Runs the workflow on pull request events to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository Content
        uses: actions/checkout@v4 # Checks out the repository content to the GitHub runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # Specifies the Python version needed
          
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Installs dependencies from requirements.txt
          
      - name: Execute Python Script
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }} # Passes secrets if needed by the script
        run: python app.py # Executes the main Python script
          
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Updated logs from main.py" --allow-empty # Commits only if there are changes
          
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # Pushes the changes back to the main branch
