name: Python Application CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Prepare Data and Artifacts
        run: |
          # Create necessary directories
          mkdir -p notebook/data
          mkdir -p artifacts

          # Check if required data files are present, otherwise download or copy them
          # Replace the URL or copy path as needed for your context
          
          # Downloading 'stud.csv' or copy from an accessible location
          if [ ! -f notebook/data/stud.csv ]; then
            echo "Downloading stud.csv..."
            curl -L -o notebook/data/stud.csv https://github.com/dilukshashamal/ML-Project/main/notebook/data/stud.csv
          fi
          
          # Downloading 'model.pkl' or copy from an accessible location
          if [ ! -f artifacts/model.pkl ]; then
            echo "Downloading model.pkl..."
            curl -L -o artifacts/model.pkl https://github.com/dilukshashamal/ML-Project/main/artifacts/model.pkl
          fi

          # Downloading 'proprocessor.pkl' or copy from an accessible location
          if [ ! -f artifacts/proprocessor.pkl ]; then
            echo "Downloading proprocessor.pkl..."
            curl -L -o artifacts/proprocessor.pkl https://github.com/dilukshashamal/ML-Project/main/artifacts/proprocessor.pkl
          fi

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest --maxfail=5 --disable-warnings
